### ISSUE TITLE
Weekly Scrum - Nov 13

### ISSUE THREAD

**Issue by PAVafaie** [FARHAN-MAHAMUD/SYSC-4806-Project#38]
Comment the following:

- what have I done this week? (with link(s) to the relevant GitHub Issue(s))
- what will I do next week? (with link(s) to the relevant GitHub Issue(s))
- what is holding me back? (if applicable)

**Comment by Hoveywan** [comment]
What have I done this week? 
This past week I aided in completing milestone 1 by primarily working on the frontend. I added the HTML views necessary to represent all of the UI pages, and I added ajax to handle the add/edit books functionality. I also modified the bookstore controller to accept these requests. This work is encompassed in #36. This was primarily completed in the PRs #10, #11, #14, and #22.

What will I do next week?
Next week I will attempt to setup an alternate repo using AWS Codestar. In order for Codestar to be implemented in a project, a new repo has to be created following the steps specific to that workflow. I will attempt to create this while maintaining the code/functionality of our main repo. Our goal is to showcase our identical application running on both Azure and AWS Codestar in order to present the differences and potential advantages/disadvantages of each. This Azure repo will continue to be our primary repo going forward. This work is encompassed in the task #26.

**Comment by subearjama** [comment]
What have I done this week?
* Added Book class that contains all the info a book has including the number of copies stored.
* Implemented integration testing in Sysc4806ProjectApplicationTests class
* Added and modified tests for BookstoreControllerTest

What will I do next week?
* Set up a basic login system using Spring framework to differentiate between owner and customer #25
* Update the html and routes accordingly to have a good UI
* Add on to test classes to check for these new changes

What is holding me back? (if applicable)
* N/A

**Comment by PAVafaie** [comment]
What have I done this week?
* Created logic used in BookstoreController for adding, deleting, and purchasing books https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/33
* Unit testing for above Bookstore methods
* Modified Jquery calls used for AJAX in https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/36

What will I do next week?
* Add a new database table to track purchase history based on users - https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/30
* Implement Jaccard distance algorithm to recommend similar books https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/30

No blockers

**Comment by ihasnaou** [comment]
What have I done this week?

- Added User class that contains all the info a user has including whether the user has owner rights
- Added UserController class that contains the application logic to do with a User
- Implemented testing for the User & User controller classes

What will I do next week?

- Finish implementing the checkout use case 
- Make more complex and robust test cases for User relates use cases

What is holding me back? (if applicable)

N/A

**Comment by FARHAN-MAHAMUD** [comment]
What have I done this week?
- Created the repository
- Setup skeleton classes so the other members can start early
- Deployed our project to Azure
- Did a lot of research on AWS and tried to find a way to easily deploy our project using the service https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/32
- Setup CI/CD in the repository to ensure that each PR requires that it builds correctly without any issues and that it gets reviewed by another team member before it gets pushed into the main branch
- Created the README, ORM diagram, and UML diagram https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/37

What will I do next week?
- Work on the front end for the Book use cases (adding and removing a book from a User's shopping cart) https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/29
- Ensure consistency between the local host version and the version on Azure https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/24
