### ISSUE TITLE
Weekly Scrum - Nov 20

### ISSUE THREAD

**Issue by FARHAN-MAHAMUD** [FARHAN-MAHAMUD/SYSC-4806-Project#46]

**Comment by PAVafaie** [comment]
What have I done this week?
* Implemented book recommendations based on Jaccard distance - integrated a new purchase history repository and recommendation service + controller for https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/30
* Created unit + integration testing for https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/30, and created a new test security configuration to work around login redirects with https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/25

What will I do next week?
* Integrate recommendation system with the front end, finishing https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/30

Blockers
* https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/47 - need checkout to be completed so that purchase history can actually be populated on front end

**Comment by FARHAN-MAHAMUD** [comment]
What have I done this week?

- Implemented the update function so now an owner can update the properties of a book https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/29
- Added the unit tests for the update function

What will I do next week?
- Record my part of the video https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/27
- Edit the entire video with my partners' section
- Implement the front end for the checkout use case https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/47

**Comment by subearjama** [comment]
What have I done this week?
* Implemented a functional login system with updated login pages and HTML routes with a redesign #41
* Included SecurityConfig class to configure Spring's Security and permissions
* Temporary in-memory user accounts used for hard coding 2 user configurations (user & owner) with encryption (no need for a sign-up page for now)
* Hid different view based on what account is logged in (A user account cannot use the owner template)

What will I do next week?
* Update the integration tests to check for these new changes as pages will always route to login without authentication
* Work on some concurrency tests #44 
* Updating the UML for Milestone 2 #49 

What is holding me back? (if applicable)
* N/A

**Comment by Hoveywan** [comment]
What have I done this week?

- Created a separate repo for AWS Codestar and got the pipeline/deployment working. AWS Codestar requires a fresh repo created by their conventions to run, in a slightly different structure then our main repo. #26 
AWS Repo: https://github.com/Hoveywan/SYSC4806-21-v2
AWS Website: http://ec2-13-59-196-47.us-east-2.compute.amazonaws.com/

What will I do next week?

- Edit the frontend organization so that the customer view is the default landing page and the owner view is an extra only available to users with the owner role #50 
- Update Ajax calls to refresh automatically on azure (currently this works locally but not azure) #24
