### ISSUE TITLE
Weekly Scrum Nov. 27, 2023

### ISSUE THREAD

**Issue by FARHAN-MAHAMUD** [FARHAN-MAHAMUD/SYSC-4806-Project#69]

**Comment by Hoveywan** [comment]
What have I done this week?

- Edited the frontend organization so that the customer view is the default landing page after login and the owner view is only available through a "Manage Store" button to users with the owner role #50 
- Updated Ajax calls to refresh automatically on azure #24 
- Updated name on website to show the logged in username rather than a default value of "Jacob"
- Updated AWS Codestar website to match milestone 2 of Azure website https://github.com/Hoveywan/SYSC4806-21-v2/pull/1

What will I do next week?

- Make it possible to navigate from the homepage to the shop view without logging in again if a user is already logged in. Currently, the homepage only navigates to the login page #64 
- Refactor and clean up code, add javadocs, remove some unneccessary or commented out sections #65

**Comment by PAVafaie** [comment]
What have I done this week?
* Finalized logic for recommendations, modified recommendation controller endpoints https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/30
* Added recommendations to front end https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/30
* Create ORM diagram for Milestone 2

What will I do next week?
* Improve customer UX so we no longer have to manually enter the ISBN of the books we want to add/remove https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/67
* Refactor, small improvements https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/65

**Comment by subearjama** [comment]
What have I done this week?
* Updated the integration tests to check for login page changes as pages will always route to login without authentication #58 
* Created ConcurrencyTest class to test the functionality of 2 users (owner & user) accessing the system simultaneously #44 
* Created the UML diagram for Milestone 2 #49
* Along with some minor fixes

What will I do next week?
* Have accounts (owner, user) linked to the users stored in the repository in order to fix recommendation feature #66 
* Add some JavaDocs and clean up code, along with some additional fixes #65 

What is holding me back? (if applicable)
* N/A

**Comment by ihasnaou** [comment]
What have I done this week?

- Update the integration tests to check for these new changes as pages will always route to login without authentication
- Updated some concurrency tests in parallel
- Finalized the readme file for each 

What will I do next week?

- Add a pop-up when checking out that lists the content of the cart before buying
- Minor refactoring
